# Generated by Django 5.0.6 on 2024-07-04 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_alter_category_options_customer_is_sale_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='is_sale',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='sale_price',
        ),
        migrations.AddField(
            model_name='product',
            name='is_sale',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='sale_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
