# Generated by Django 5.0.6 on 2024-07-08 14:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0005_order_date_shipped_order_shipped'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='date_shipped',
        ),
        migrations.RemoveField(
            model_name='order',
            name='shipped',
        ),
    ]
